import Vue from "vue";
import { Table } from "iview";
import { Page } from "iview";
import { Input } from "iview";
// import { Modal } from "iview";
// import { Form } from "iview";
// import { FormItem } from "iview";
// import { Select } from "iview";
// import { Option } from "iview";
// import { Row } from "iview";
// import { Col } from "iview";
// import { RadioGroup } from "iview";
// import { Radio } from "iview";
// import { Button } from "iview";

Vue.component("Table", Table);
Vue.component("Page", Page);
Vue.component("Input", Input);
// Vue.component("Modal", Modal);
// Vue.component("From", Form);
// Vue.component("FormItem", FormItem);
// Vue.component("Select", Select);
// Vue.component("Option", Option);
// Vue.component("Row", Row);
// Vue.component("Col", Col);
// Vue.component("RadioGroup", RadioGroup);
// Vue.component("Button", Button);
// Vue.component("Radio", Radio);

import "iview/dist/styles/iview.css";
